version: "3.9"

services:
  web:
    build: .
    restart: always
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 --timeout 30000
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7

  celery:
    build: .
    restart: always
    command: celery -A api worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - db

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: