# Generated by Django 5.0.1 on 2024-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanmar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='back_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
